[workspace]
authors = ["Hiroyuki Okada <okdhryk@gmail.com>"]
channels = ["robostack-humble", "conda-forge"]
name = "my_ros2_project"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
sim = "ros2 run turtlesim turtlesim_node"
build = { cmd = "colcon build --symlink-install", inputs = ["src"] }
hello = { cmd = "ros2 run my_package my_node", depends-on = ["build"] }

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-turtlesim = ">=1.4.2,<2"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
ros-humble-ament-cmake-auto = ">=1.3.12,<2"
compilers = ">=1.11.0,<2"
pkg-config = ">=0.29.2,<0.30"
cmake = ">=4.2.0,<5"
ninja = ">=1.13.2,<2"

[activation]
scripts = ["install/setup.sh"]
